# Generated by Django 3.2.11 on 2022-05-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='about_heading',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='about_subheading',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='contact_heading',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='contact_subheading',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='home_heading',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='home_subheading',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='post_heading',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='post_subheading',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='weibo_link',
            field=models.URLField(blank=True, null=True, verbose_name='微博链接'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='zhihu_link',
            field=models.URLField(blank=True, null=True, verbose_name='知乎链接'),
        ),
    ]
