# Generated by Django 3.2.11 on 2022-05-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_aboutmanager_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='links',
            name='title',
            field=models.CharField(max_length=50, verbose_name='昵称'),
        ),
    ]
